bdhospital/urls.py
from django.urls import path
from . import views

app_name = 'Registro'
urlpatterns = [
    path('', views.index, name='index'),
    path('paciente', views.paciente, name='paciente'),
    path('medico', views.medico, name='medico'),
    path('consulta', views.consulta, name='consulta'),
    path('tratamiento', views.tratamiento, name='tratamiento'),
    path('paciente_tratamiento', views.paciente_tratamiento, name='paciente_tratamiento'),
    path('FormMedico', views.FormMedico, name='FormMedico'),
    path('FormPaciente', views.FormPaciente, name='FormPaciente'),
    path('FormConsulta', views.FormConsulta, name='FormConsulta'),
    path('FormTratamiento', views.FormTratamiento, name='FormTratamiento'),
    path('Formpaciente_tratamiento', views.Formpaciente_tratamiento, name='Formpaciente_tratamiento'),
    path('UpdatePaciente/<int:paciente_id>', views.UpdatePaciente, name='UpdatePaciente'),
    path('UpdateMedico/<int:medico_id>', views.UpdateMedico, name='UpdateMedico'),
    path('UpdateConsulta/<int:consulta_id>', views.UpdateConsulta, name='UpdateConsulta'),
    path('UpdateTratamiento/<int:tratamiento_id>', views.UpdateTratamiento, name='UpdateTratamiento'),
    path('DeletePaciente/<int:paciente_id>', views.DeletePaciente, name='DeletePaciente'),
    path('DeleteMedico/<int:medico_id>', views.DeleteMedico, name='DeleteMedico'),
    path('DeleteTratamiento/<int:tratamiento_id>', views.DeleteTratamiento, name='DeleteTratamiento'),
     path('DeleteConsulta/<int:consulta_id>', views.DeleteConsulta, name='DeleteConsulta')
]

hospital/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bdhospital.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bdhospital/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Paciente(models.Model):
    nombre = models.CharField(max_length=255)
    numero_seguro = models.IntegerField(unique=True)
    fecha_de_nacimiento = models.DateField()

    def __str__(self):
        return self.nombre

class Medico(models.Model):
    nombre = models.CharField(max_length=255)
    especializacion = models.CharField(max_length=255)

    def __str__(self):
        return self.especializacion

class Consulta(models.Model):
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    medico = models.ForeignKey(Medico, on_delete=models.CASCADE)
    fecha = models.DateTimeField(default=timezone.now)
    motivo  = models.CharField(max_length=255)
    diagnostico = models.CharField(max_length=255)

    def __str__(self):
       return self.fecha.strftime("%d-%m-%Y")
    
class Tratamiento(models.Model):
    medicamento = models.CharField(max_length=255)
    terapia =  models.CharField(max_length=255)

    def __str__(self):
        return self.medicamento

class Paciente_Tratamiento(models.Model):
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    tratamiento = models.ForeignKey(Tratamiento, on_delete=models.CASCADE)
    consulta = models.ForeignKey(Consulta, on_delete=models.CASCADE)

bdhospital/forms.py
from . import models
from django.forms import ModelForm

class PacienteForm(ModelForm):
    class Meta:
        model = models.Paciente
        fields = ['nombre','numero_seguro','fecha_de_nacimiento']

class MedicoForm(ModelForm):
    class Meta:
        model = models.Medico
        fields = ['nombre','especializacion']

class ConsultaForm(ModelForm):
    class Meta:
        model = models.Consulta
        fields = ['paciente','medico','motivo','diagnostico']

class TratamientoForm(ModelForm):
    class Meta:
        model = models.Tratamiento
        fields = ['medicamento','terapia']

class Paciente_TratemientoForm(ModelForm):
    class Meta:
        model = models.Paciente_Tratamiento
        fields = ['paciente','tratamiento','consulta']

bdhospital/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from .models import Paciente, Medico, Consulta, Tratamiento,Paciente_Tratamiento
from .forms import PacienteForm,MedicoForm,ConsultaForm,TratamientoForm,Paciente_TratemientoForm
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def index(request):
    pacientes = Paciente.objects.all()
    medico = Medico.objects.all()
    consulta = Consulta.objects.all()
    tratamiento = Tratamiento.objects.all()
    paciente_tratamiento = Paciente_Tratamiento.objects.all()
    return render(
        request,
        'index.html',
        context={'pacientes':pacientes,'medico':medico,'consulta':consulta,'tratamiento':tratamiento,'paciente_tratamiento':paciente_tratamiento}
    )

@login_required
def paciente(request):
    pacientes = Paciente.objects.all()
    return render(
        request,
        'paciente.html',
        context={'pacientes':pacientes}
    )

@login_required
def medico(request):
    medico = Medico.objects.all()
    return render(
        request,
        'medico.html',
        context={'medico':medico}
    )

@login_required
def consulta(request):
    consulta = Consulta.objects.all()
    return render(
        request,
        'consulta.html',
        context={'consulta':consulta}
    )

@login_required
def tratamiento(request):
    tratamiento = Tratamiento.objects.all()
    return render(
        request,
        'tratamiento.html',
        context={'tratamiento':tratamiento}
    )

@login_required
def paciente_tratamiento(request):
    paciente_tratamiento = Paciente_Tratamiento.objects.all()
    return render(
        request,
        'paciente_tratamiento.html',
        context={'paciente_tratamiento':paciente_tratamiento}
    )

@login_required
def FormPaciente(request): 
    if request.method == 'POST':
        form = PacienteForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/paciente')
    else:
        form = PacienteForm()
    
    return render(
        request,
        'Paciente/FormPaciente.html',
        {'form': form}
    )

@login_required
def FormMedico(request): 
    if request.method == 'POST':
        form = MedicoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/medico')
    else:
        form = MedicoForm()
    
    return render(
        request,
        'Medico/FormMedico.html',
        {'form': form}
    )

@login_required
def FormConsulta(request): 
    paciente = Paciente.objects.all()
    medico = Medico.objects.all()
    if request.method == 'POST':
        form = ConsultaForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/consulta')
    else:
        form = ConsultaForm()
    
    return render(
        request,
        'Consulta/FormConsulta.html',
        {'form': form, 'paciente':paciente, 'medico':medico}
    )

@login_required
def FormTratamiento(request): 
    if request.method == 'POST':
        form = TratamientoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/tratamiento')
    else:
        form = TratamientoForm()
    
    return render(
        request,
        'Tratamiento/FormTratamiento.html',
        {'form': form}
    )

@login_required
def Formpaciente_tratamiento(request): 
    paciente = Paciente.objects.all()
    tratamiento = Tratamiento.objects.all()
    consulta = Consulta.objects.all()
    if request.method == 'POST':
        form = Paciente_TratemientoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/paciente_tratamiento')
    else:
        form = Paciente_TratemientoForm()
    
    return render(
        request,
        'Paciente_Tratamiento/Paciente_Tratamiento.html',
        {'form': form,'paciente':paciente,'tratamiento':tratamiento,'consulta':consulta}
    )

@login_required
def UpdatePaciente(request, paciente_id):
    paciente = get_object_or_404(Paciente, id=paciente_id)
    if request.method == 'POST':
        form = PacienteForm(request.POST, instance=paciente)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/paciente')
    else:
        form  = PacienteForm(instance=paciente)
    return render(
        request,
        'Paciente/UpdatePaciente.html',
        context={'form': form, 'paciente':paciente }
    )

@login_required
def UpdateMedico(request, medico_id):
    medico = get_object_or_404(Medico, id=medico_id)
    if request.method == 'POST':
        form = MedicoForm(request.POST, instance=medico)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/medico')
    else:
        form  = MedicoForm(instance=medico)
    return render(
        request,
        'Medico/UpdateMedico.html',
        context={'form': form, 'medico':medico }
    )

@login_required
def UpdateConsulta(request, consulta_id):
    paciente = Paciente.objects.all()
    medico = Medico.objects.all()
    consulta = get_object_or_404(Consulta, id=consulta_id)
    if request.method == 'POST':
        form = ConsultaForm(request.POST, instance=consulta)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/consulta')
    else:
        form  = ConsultaForm(instance=consulta)
    return render(
        request,
        'Consulta/UpdateConsulta.html',
        context={'form': form, 'consulta':consulta,'paciente':paciente,'medico':medico }
    )

@login_required
def UpdateTratamiento(request, tratamiento_id):
    tratamiento = get_object_or_404(Tratamiento, id=tratamiento_id)
    if request.method == 'POST':
        form = TratamientoForm(request.POST, instance=tratamiento)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/tratamiento')
    else:
        form  = TratamientoForm(instance=tratamiento)
    return render(
        request,
        'Tratamiento/UpdateTratamiento.html',
        context={'form': form }
    )

@login_required
def DeletePaciente(request, paciente_id):
    eliminar = get_object_or_404(Paciente, id=paciente_id)
    if request.method == 'POST':
        eliminar.delete()
        return HttpResponseRedirect('/paciente')
    return render(
        request,
        'Paciente/DeletePaciente.html',
        context={'eliminar': eliminar}
    )

@login_required
def DeleteMedico(request, medico_id):
    eliminar = get_object_or_404(Medico, id=medico_id)
    if request.method == 'POST':
        eliminar.delete()
        return HttpResponseRedirect('/medico')
    return render(
        request,
        'Medico/DeleteMedico.html',
        context={'eliminar': eliminar}
    )

@login_required
def DeleteTratamiento(request, tratamiento_id):
    eliminar = get_object_or_404(Tratamiento, id=tratamiento_id)
    if request.method == 'POST':
        eliminar.delete()
        return HttpResponseRedirect('/tratamiento')
    return render(
        request,
        'Tratamiento/DeleteTratamiento.html',
        context={'eliminar': eliminar}
    )

@login_required
def DeleteConsulta(request, consulta_id):
    eliminar = get_object_or_404(Consulta, id=consulta_id)
    if request.method == 'POST':
        eliminar.delete()
        return HttpResponseRedirect('/consulta')
    return render(
        request,
        'Consulta/DeleteConsulta.html',
        context={'eliminar': eliminar}
    )

bdhospital/templates/consulta.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
  <link rel="stylesheet" href="../css/index.css" />
  <title>Hospital</title>
</head>

<body>
  <div style="display: flex">
    <div class="d-flex flex-column flex-shrink-0 p-3 bg-body-tertiary height:100vh" style="width: 280px; height: 100vh">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <svg class="bi pe-none me-2" width="40" height="32">
          <use xlink:href="#bootstrap"></use>
        </svg>
        <span class="fs-4">Hospital</span>
      </a>
      <hr />
      <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
          <a href="/" class="nav-link link-body-emphasis" aria-current="page">
            <svg class="bi pe-none me-2" width="16" height="16">
              <use xlink:href="#home"></use>
            </svg>
            Dashboard
          </a>
        </li>
        <li>
          <a href="/paciente" class="nav-link link-body-emphasis">
            <svg class="bi pe-none me-2" width="16" height="16">
              <use xlink:href="#speedometer2"></use>
            </svg>
            Paciente
          </a>
        </li>
        <li>
          <a href="/medico" class="nav-link link-body-emphasis">
            <svg class="bi pe-none me-2" width="16" height="16">
              <use xlink:href="#table"></use>
            </svg>
            Medico
          </a>
        </li>
        <li>
          <a href="/consulta" class="nav-link active">
            <svg class="bi pe-none me-2" width="16" height="16">
              <use xlink:href="#grid"></use>
            </svg>
            Consulta
          </a>
        </li>
        <li>
          <a href="/tratamiento" class="nav-link link-body-emphasis">
            <svg class="bi pe-none me-2" width="16" height="16">
              <use xlink:href="#people-circle"></use>
            </svg>
            Tratamiento
          </a>
        </li>
        <li>
          <a href="/paciente_tratamiento" class="nav-link link-body-emphasis">
            <svg class="bi pe-none me-2" width="16" height="16">
              <use xlink:href="#grid"></use>
            </svg>
            Paciente Tratamiento
          </a>
        </li>
      </ul>
      <hr />
      <div class="dropdown">
        <a href="#" class="d-flex align-items-center link-body-emphasis text-decoration-none dropdown-toggle"
          data-bs-toggle="dropdown" aria-expanded="false">
          <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2" />
          <strong>Administrador</strong>
        </a>
        <ul class="dropdown-menu text-small shadow">
          <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <li>
              <button type="submit" class="dropdown-item">Cerrar sesión</button>
            </li>
          </form>
        </ul>
      </div>
    </div>
    <div>
      <h1 style="margin-left: 2%;">Consultas</h1>
      <br /><br />
      <div>
        <a href="/FormConsulta" style="text-decoration: none;">
          <button style="display: flex; margin-left: auto" class="btn btn-primary">
            Crear Consulta
          </button>
        </a>
      </div>
      <table class="table" style="width: 130vh;margin-left: 2%;">
        <thead>
          <tr>
            <th scope="col">No. Pacientes</th>
            <th scope="col">Paciente</th>
            <th scope="col">Medico</th>
            <th scope="col">Fecha</th>
            <th scope="col">Motivo</th>
            <th scope="col">Diagnostico</th>
          </tr>
        </thead>
        <tbody>
          {% for consulta in consulta %}
          <tr>
            <th scope="row">{{consulta.id}}</th>
            <td>{{consulta.paciente}}</td>
            <td>{{consulta.medico.nombre}}</td>
            <td>{{consulta.fecha}}</td>
            <td>{{consulta.motivo}}</td>
            <td>{{consulta.diagnostico}}</td>
            <td><a href="{% url 'Registro:UpdateConsulta' consulta.id %}"><Button
                  class="btn btn-success">Editar</Button></a>
            </td>
            <td><a href="{% url 'Registro:DeleteConsulta' consulta.id %}"><button
                  class="btn btn-danger">Eliminar</button></a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</body>

</html>

bdhospital/templates/medico.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
  <link rel="stylesheet" href="../css/index.css" />
  <title>Hospital</title>
</head>

<body>
  <div style="display: flex">
    <div class="d-flex flex-column flex-shrink-0 p-3 bg-body-tertiary height:100vh" style="width: 280px; height: 100vh">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <svg class="bi pe-none me-2" width="40" height="32">
          <use xlink:href="#bootstrap"></use>
        </svg>
        <span class="fs-4">Hospital</span>
      </a>
      <hr />
      <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
          <a href="/" class="nav-link link-body-emphasis" aria-current="page">
            <svg class="bi pe-none me-2" width="16" height="16">
              <use xlink:href="#home"></use>
            </svg>
            Dashboard
          </a>
        </li>
        <li>
          <a href="/paciente" class="nav-link link-body-emphasis">
            <svg class="bi pe-none me-2" width="16" height="16">
              <use xlink:href="#speedometer2"></use>
            </svg>
            Paciente
          </a>
        </li>
        <li>
          <a href="/medico" class="nav-link active">
            <svg class="bi pe-none me-2" width="16" height="16">
              <use xlink:href="#table"></use>
            </svg>
            Medico
          </a>
        </li>
        <li>
          <a href="/consulta" class="nav-link link-body-emphasis">
            <svg class="bi pe-none me-2" width="16" height="16">
              <use xlink:href="#grid"></use>
            </svg>
            Consulta
          </a>
        </li>
        <li>
          <a href="/tratamiento" class="nav-link link-body-emphasis">
            <svg class="bi pe-none me-2" width="16" height="16">
              <use xlink:href="#people-circle"></use>
            </svg>
            Tratamiento
          </a>
        </li>
        <li>
          <a href="/paciente_tratamiento" class="nav-link link-body-emphasis">
            <svg class="bi pe-none me-2" width="16" height="16">
              <use xlink:href="#grid"></use>
            </svg>
            Paciente Tratamiento
          </a>
        </li>
      </ul>
      <hr />
      <div class="dropdown">
        <a href="#" class="d-flex align-items-center link-body-emphasis text-decoration-none dropdown-toggle"
          data-bs-toggle="dropdown" aria-expanded="false">
          <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2" />
          <strong>Administrador</strong>
        </a>
        <ul class="dropdown-menu text-small shadow">
          <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <li>
              <button type="submit" class="dropdown-item">Cerrar sesión</button>
            </li>
          </form>
        </ul>
      </div>
    </div>
    <div>
      <h1 style="margin-left: 2%;">Medico</h1>
      <br /><br />
      <a href="/FormMedico" style="text-decoration: none;">
        <button style="display: flex; margin-left: auto;" class="btn btn-primary">
          Nuevo Medico
        </button>
      </a>

      <table class="table" style="width: 130vh;margin-left: 2%;">
        <thead>
          <tr>
            <th scope="col">No. Medico</th>
            <th scope="col">Nombre</th>
            <th scope="col">Especialización</th>
          </tr>
        </thead>
        <tbody>
          {% for medico in medico %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{medico.nombre}}</td>
            <td>{{medico.especializacion}}</td>
            <td><a href="{% url 'Registro:UpdateMedico' medico.id %}"><Button
                  class="btn btn-success">Editar</Button></a>
            </td>
            <td><a href="{% url 'Registro:DeleteMedico' medico.id %}"><button
                  class="btn btn-danger">Eliminar</button></a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</body>

</html>

bdhospital/templates/paciente.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
  <title>Hospital</title>
</head>

<body>
  <div style="display: flex">
    <div class="d-flex flex-column flex-shrink-0 p-3 bg-body-tertiary height:100vh" style="width: 280px; height: 100vh">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <svg class="bi pe-none me-2" width="40" height="32">
          <use xlink:href="#bootstrap"></use>
        </svg>
        <span class="fs-4">Hospital</span>
      </a>
      <hr />
      <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
          <a href="/" class="nav-link link-body-emphasis" aria-current="page">
            <svg class="bi pe-none me-2" width="16" height="16">
              <use xlink:href="#home"></use>
            </svg>
            Dashboard
          </a>
        </li>
        <li>
          <a href="#" class="nav-link active">
            <svg class="bi pe-none me-2" width="16" height="16">
              <use xlink:href="#speedometer2"></use>
            </svg>
            Paciente
          </a>
        </li>
        <li>
          <a href="/medico" class="nav-link link-body-emphasis">
            <svg class="bi pe-none me-2" width="16" height="16">
              <use xlink:href="#table"></use>
            </svg>
            Medico
          </a>
        </li>
        <li>
          <a href="/consulta" class="nav-link link-body-emphasis">
            <svg class="bi pe-none me-2" width="16" height="16">
              <use xlink:href="#grid"></use>
            </svg>
            Consulta
          </a>
        </li>
        <li>
          <a href="/tratamiento" class="nav-link link-body-emphasis">
            <svg class="bi pe-none me-2" width="16" height="16">
              <use xlink:href="#people-circle"></use>
            </svg>
            Tratamiento
          </a>
        </li>
        <li>
          <a href="/paciente_tratamiento" class="nav-link link-body-emphasis">
            <svg class="bi pe-none me-2" width="16" height="16">
              <use xlink:href="#grid"></use>
            </svg>
            Paciente Tratamiento
          </a>
        </li>
      </ul>
      <hr />
      <div class="dropdown">
        <a href="#" class="d-flex align-items-center link-body-emphasis text-decoration-none dropdown-toggle"
          data-bs-toggle="dropdown" aria-expanded="false">
          <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2" />
          <strong>Administrador</strong>
        </a>
        <ul class="dropdown-menu text-small shadow">
          <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <li>
              <button type="submit" class="dropdown-item">Cerrar sesión</button>
            </li>
          </form>
        </ul>
      </div>
    </div>
    <div>
      <h1 style="margin-left: 2%;">Pacientes</h1>
      <br /><br />
      <div>
        <a style="text-decoration: none;" href="/FormPaciente">
          <button style="display: flex; margin-left: auto" class="btn btn-primary">
            Nuevo Pacientes
          </button>
        </a>
      </div>
      <table class="table" style="width: 130vh;margin-left: 2%;">
        <thead>
          <tr>
            <th scope="col">No. Pacientes</th>
            <th scope="col">Nombre</th>
            <th scope="col">Numero Seguro</th>
            <th scope="col">Fecha de nacimiento</th>
          </tr>
        </thead>
        <tbody>
          {% for paciente in pacientes %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{paciente.nombre}}</td>
            <td>{{paciente.numero_seguro}}</td>
            <td>{{paciente.fecha_de_nacimiento}}</td>
            <td><a href="{% url 'Registro:UpdatePaciente' paciente.id %}"><Button
                  class="btn btn-success">Editar</Button></a></td>
            <td><a href="{% url 'Registro:DeletePaciente' paciente.id %}"><button
                  class="btn btn-danger">Eliminar</button></a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</body>

</html>